### ISSUE TITLE
Pseudopoints

### ISSUE THREAD

**Issue by paulbrodersen** [duhaime/lloyd#6]
Hi, 

I saw the [stackoverflow post](https://stackoverflow.com/q/52506681/2912349) and read your blog. Both mention the use of pseudopoints to constrain the layout. I tried to implement this idea but could not get it to work. I then read your source code. You are still computing the bounding box / pseudopoints /  `bb_points`; however, as far as I can tell, you are not using them anywhere, at least not in the latest commits (unless I am very blind today). If you have a moment, could you share your thoughts on the utility of pseudopoints? 

Thank you,
Paul

**Comment by paulbrodersen** [comment]
Thanks for the quick reply. 

> I'm curious to see your data--are you able to share it? That's probably the fastest way to figure out what's gone awry. Even some characteristics of the distribution would do.

I was just playing around with random points sampled from a uniform distribution. I am the maintainer of a network plotting library [netgraph](https://github.com/paulbrodersen/netgraph), and I was planning on using the Voronoi heuristic to post-process node layouts. Basically, a lot of layouts simulate networks as a system of springs such that connected nodes attract each other and unconnected nodes repel each other. However, if the spring constant is set too high, you often get node overlaps or nodes that are very clumped together such that it becomes hard to see the connectivity.  

> The domains attribute is what actually constrains the layout.

That is exactly what I thought. 

> All of this said, I've been using pointgrid to jitter points recently. It's simpler!

Thank you for the reference. That looks very interesting. Not something I would use for postprocessing network diagrams but it might very useful to make t-SNE or UMAP projections more readable. 

Again, thank you for your time, and have a good week!

**Comment by duhaime** [comment]
🙏 Thanks for the follow up! Netgraph looks cool!

**Comment by sweetbeet** [comment]
Hi! One thing I wanted a bit more clarification on is about the bounding points. Let's say I want to have a rectangular box, so I have a width and height, thus my bounding box would look like (0,0), (0,height), (width, 0), (width, height). Currently I'I'm generating let's say 10 random coordinates within the allowable ranges and I want to relax their Voronoi plot a few times. I have hardcoded the values for domain to be 0 for min in x and y, and width and height for x and y max respectively. I'm noticing some of my 10 points (sometimes one of them, sometimes 2 of them) get lost (?) as I'm running relax on them, which leads to believe every time we run relax (and thus Voronoi again) some points are **assumed** to be psudopoints and get eliminated? But that would mean some data would be lost? I'm really confused about this, I'd appreciate some clarification on the idea of psudopoints here. Thanks!
